_parent_: projects/neuralangelo/configs/base.yaml
data:
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: /content/drive/MyDrive/neuralangelo_datasets/Ignatuis/Ignatius
    train:
        image_size:
        - 835
        - 1500
    type: projects.neuralangelo.data
    val:
        image_size:
        - 300
        - 538
model:
    appear_embed:
        enabled: false
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 8
            mlp:
                inside_out: false
